# Generated by Django 4.2 on 2023-11-12 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_category_product_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='details',
            new_name='detail',
        ),
    ]
