# Generated by Django 4.2 on 2023-11-22 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_productrating_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='details',
            new_name='detail',
        ),
    ]
